### ISSUE TITLE
Error playing videos in fall flashback

### ISSUE THREAD

**Issue by sirois44** [cfx/videojs-playlist#1]
testing this out in Firefox 9.0.1 and I'm having issues playing the 2nd video in the playlist. If you click the 2nd video, then click in the div/area where the video should be playing then it will actually load. Happening to other videos as well.

I might be clicking too fast and not letting the javascript events time, anyone else having the same problem.

Working flawless on ipad safari and Chrome though!!!

**Comment by cfx** [comment]
Thanks for your feedback. I will take a look at it today

**Comment by cfx** [comment]
Flash fallback mode:
When you click on the image thumb and then click in the video area - video will be paused (and loading into the buffer). Its a normal behaviour I think. It works the same in html5 mode. I've noticed that pause (by clicking in video area) doesn't work on Chrome.

HTML5 mode:
In the dev.html.example videos #2 #4 and #6 are only in mp4 format. FF doesn't support mp4.

Best,
Jozef
